((org-mode . ((mode . auto-fill)
             (org-export-with-author . nil)
             (org-hugo-base-dir . "~/repo/keido-hugo")
             (org-hugo-section . "notes")
             (org-hugo-export-with-toc . nil))))
