:PROPERTIES:
:ID:       4401310f-222c-4031-8bd3-886830619480
:ROAM_ALIASES: nothung
:END:
#+STARTUP: overview
#+filetags: :Emacs:
#+TITLE: ⚡My Emacs Config - Nothung

Emacsを極限まで叩き上げ, なによりも強靭な刃にする. [[https://www.youtube.com/watch?v=04L18rQiIgw][一つのことを極める]].

副題のノートォング(Nothung)とは勇者ジークフリートの持つ伝説の剣である.

- https://www.youtube.com/watch?v=B6wChr_geAg
- https://www.youtube.com/watch?v=v31N8zxGhQY

---

packageの並び順は [[https://github.com/hlissner/doom-emacs][Doom Emacs]] の [[https://github.com/hlissner/doom-emacs/blob/develop/docs/modules.org][Molule Index]] (アルファベット順)に従う.

ref: https://github.com/tsu-nera/nothung

いつも忘れるDoom Emacs Configuration記法は [[https://github.com/hlissner/doom-emacs/blob/master/docs/getting_started.org#configuring-doom][ここ]].

- use-package! は:defer, :hook, :commands, or :after が省略されると起動時に loadされる.
- after! は package が load されたときに評価される.
- add-hook! は mode 有効化のとき. setq-hook!は equivalent.

どれを使うかの正解はないがすべて use-package!だと起動が遅くなるので
場合によってカスタマイズせよ，とのこと.

ref. 過去の設定は[[https://github.com/tsu-nera/dotfiles/tree/master/.emacs.d/inits][こちら]]. 

#+begin_src emacs-lisp :tangle yes
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
(load-file "~/.doom.d/private/config.el")

;; 自作関数
(load-file "~/.doom.d/utils.el")
#+end_src

* App

** eww

Emacsのテキストブラウザ([[https://www.gnu.org/software/emacs/manual/html_mono/eww.html][Manual]])

notes:
- ewwを起動しただけだとminibufferなのでC-gで消えてしまうので大きくC-x 1とかで大きくする.
- C-u M-x ewwでひとつのbufferを使いまわすのではなく別のBufferでewwを開く.
- M-RETでURLを新しいBufferで開く.
- Doom EmacsだとC-c s o(online)でいろいろと検索できる(w/Chrome). helm-google-suggest的な.

#+begin_src emacs-lisp :tangle yes
(use-package! eww
  :bind
  ("C-c s w" . eww-search-words)
  ("C-c o w" . eww-open-in-new-buffer))
#+end_src

- ace-linkをつかうとewwのlinkをインタラクティブに選択できて便利.

#+begin_src emacs-lisp :tangle yes
(use-package! ace-link
  :config
  (eval-after-load 'eww '(define-key eww-mode-map "f" 'ace-link-eww))
  (ace-link-setup-default)
  (define-key org-mode-map (kbd "M-o") 'ace-link-org))
#+end_src

** Pocket

あとで読むサービス.

#+begin_src emacs-lisp :tangle no
(global-set-key (kbd "C-x w p") 'pocket-reader)
(use-package! pocket-reader
  :bind
  ("C-x w l" . pocker-reader-add-link)
  :config
  (setq pocket-reader-open-url-default-function #'eww)
  (setq pocket-reader-pop-to-url-default-function #'eww))
#+end_src

** RSS(Elfeed)

#+begin_src emacs-lisp :tangle no
;; elfeed
(global-set-key (kbd "C-x w w") 'elfeed)
(use-package! elfeed
  :config
  (setq elfeed-feeds
        '(
          ("https://yuchrszk.blogspot.com/feeds/posts/default" blog) ; パレオな男
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCFo4kqllbcQ4nV83WCyraiw" youtube) ; 中田敦彦
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCFdBehO71GQaIom4WfVeGSw" youtube) ;メンタリストDaiGo
          ("https://www.youtube.com/feeds/videos.xml?playlist_id=PL3N_SB4Wr_S2cGYuI02bdb4UN9XTZRNDu" youtube) ; 与沢の流儀
          ("http://www.aaronsw.com/2002/feeds/pgessays.rss" blog) ; Paul Graham
          ))
  (setq-default elfeed-search-filter "@1-week-ago +unread ")
  (defun elfeed-search-format-date (date)
    (format-time-string "%Y-%m-%d %H:%M" (seconds-to-time date)))
  )
#+end_src

** Habitica

#+begin_src emacs-lisp :tangle no
(use-package! habitica
  :commands habitica-tasks
  :init
  (bind-key "C-x t g" 'habitica-tasks)
  :config
  (setq habitica-show-streak t)
  (setq habitica-turn-on-highlighting nil))
#+end_src

** Twitter

もうメンテされてない. 

#+begin_src emacs-lisp :tangle no
;; App
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; twittering-mode
;; この設定がないと認証が失敗した.
;; twittering-oauth-get-access-token: Failed to retrieve a request token
(use-package! twittering-mode
  :init
  (setq twittering-allow-insecure-server-cert t))
#+end_src

** Tidalcycles

音楽

https://tidalcycles.org/docs/getting-started/editor/Emacs

#+begin_src emacs-lisp :tangle no
(use-package! tidal
  ;; :init
  ;; (setq tidal-boot-script-path "~/.cabal/share/x86_64-osx-ghc-8.8.4/tidal-1.7.4/BootTidal.hs")
  )
#+end_src

* Checkers

#+begin_src emacs-lisp :tangle yes
;; Checkers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#+end_src

* Completion

** company-mode

#+begin_src emacs-lisp :tangle yes
;; Completion
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; org-roam の completion-at-point が動作しないのはこいつかな...
;; (add-hook! 'org-mode-hook (company-mode -1))
;; company はなにげに使いそうだからな，TAB でのみ補完発動させるか.
(setq company-idle-delay nil)
(global-set-key (kbd "TAB") #'company-indent-or-complete-common)
#+end_src

** avy/swiper

検索強化. 

#+begin_src emacs-lisp :tangle yes
(use-package! avy
  :bind
  ("C-x ," . avy-goto-char) ;; doom の keybind 上書き.
  ("C-c g l" . avy-goto-line) ;; doom の keybind 上書き.
  ("C-c s c". avy-goto-word-1))
(global-set-key (kbd "C-c g L") 'consult-goto-line)

;; うまく動かないので封印 doom との相性が悪いのかも.
;; ひとまず migemo したいときは isearch で対応.
;; (use-package! avy-migemo
;;  :after migemo
;;  :bind
;;  ("M-g m m" . avy-migemo-mode)
;;  ("M-g c" . avy-migemo-goto-char-timer) ;; doom の keybind 上書き.
;;  :config
;;  (avy-migemo-mode 1)
;;  (setq avy-timeout-seconds nil))

;; Vertico使用のためswiperとivyは無効化
;; (use-package! swiper
;;   :config
;;   (ivy-mode 1))


  
;; avy-migemo-e.g.swiper だけバクる
;; https://github.com/abo-abo/swiper/issues/2249
;;(after! avy-migemo
;;  (require 'avy-migemo-e.g.swiper))
#+end_src

** affe

fuzzy find. あいまい検索 for consult.

https://github.com/minad/affe

#+begin_src emacs-lisp :tangle yes
(use-package! affe
  :after consult
  :config
  (defun affe-orderless-regexp-compiler (input _type)
    (setq input (orderless-pattern-compiler input))
    (cons input (lambda (str) (orderless--highlight input str))))
  (setq affe-regexp-compiler #'affe-orderless-regexp-compiler))
#+end_src

** all-the-icons-completion

https://github.com/iyefrat/all-the-icons-completion

#+begin_src emacs-lisp :tangle no
(use-package! all-the-icons-completion
  :init
  (all-the-icons-completion-mode))
(add-hook! marginalia-mode-hook #'all-the-icons-completion-marginalia-setup)
#+end_src

** Copilot.el

https://github.com/copilot-emacs/copilot.el

Strongly recommend to enable childframe option in company module ((company +childframe)) to prevent overlay conflict.

#+begin_src emacs-lisp :tangle no
;; accept completion from copilot and fallback to company
(use-package! copilot
  :hook (prog-mode . copilot-mode)
  :bind (:map copilot-completion-map
              ("<tab>" . 'copilot-accept-completion)
              ("TAB" . 'copilot-accept-completion)
              ("C-TAB" . 'copilot-accept-completion-by-word)
              ("C-<tab>" . 'copilot-accept-completion-by-word)))
#+end_src

* Config

#+begin_src emacs-lisp :tangle yes
;; Config
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; doom specific config
;; (setq user-full-name "John Doe"
;;      user-mail-address "john@doe.com")
(setq confirm-kill-emacs nil) ; 終了時の確認はしない.

;; フルスクリーンで Emacs 起動
;; ブラウザと並べて表示することが多くなったのでいったんマスク
;; (add-to-list 'initial-frame-alist '(fullscreen . maximized))

;; This is to use pdf-tools instead of doc-viewer
(use-package! pdf-tools
  :config
  (pdf-tools-install)
  ;; This means that pdfs are fitted to width by default when you open them
  (setq-default pdf-view-display-size 'fit-width)
  :custom
  (pdf-annot-activate-created-annotations t "automatically annotate highlights"))

;; projectileの検索スピードを上げる
(setq projectile-indexing-method 'alien)

;; グローバルに有効化
(global-auto-revert-mode 1)

;; custom-fileの設定
(setq custom-file (expand-file-name "custom.el" doom-user-dir))
(when (file-exists-p custom-file)
  (load custom-file))
#+end_src

* Editor
#+begin_src emacs-lisp :tangle yes
;; Editor
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; 英数字と日本語の間にスペースをいれる.
;;(use-package! pangu-spacing
;;  :config
;;  (global-pangu-spacing-mode 1)
  ;; 保存時に自動的にスペースを入れるのを抑止.あくまで入力時にしておく.
;;  (setq pangu-spacing-real-insert-separtor nil))

;; 記号の前後にスペースを入れる.
(use-package! electric-operator)
(add-hook! 'org-mode-hook #'electric-operator-mode)
#+end_src

** cua-mode

#+begin_src emacs-lisp :tangle yes
(cua-mode t)
(setq cua-enable-cua-keys nil) 
#+end_src

** 改行(newline)と折り返し(wrap)

まず改行(newline)と折り返し(wrap)の２つの概念があることに注意. 

方針として自動改行は無効, 自動折り返しは許す. 

auto-fill-modeで自動改行される. これは無効にする. 

追記: 方針変更. コードではauto-fillを許す. そして単に(auto-fill-mode -1)をところでmodeのhookによって再度有効になる気がする. 

#+Begin_src emacs-lisp :tangle yes
;; (auto-fill-mode -1)
#+end_src

問題はMarkdownやOrg-modeでautl-fillが発動して改行されるところ. org-modeで再度hookが走り有効になる気がするのでコレで息を止める. 

->息が止まらないので諦めた. いくら無効にしてもorg-mode-hookの延長でauto-fill-modeをonにしてしまう人がいる. そしてその犯人が誰か２時間追求しても結局わからない. Doom Emacsの設定の仕業はある. 

#+begin_src emacs-lisp :tangle yes
(auto-fill-mode -1)
(remove-hook 'org-mode-hook #'auto-fill-mode)
;; (remove-hook 'org-mode-hook #'turn-on-auto-fill)
;; (remove-hook 'text-mode-hook #'auto-fill-mode)
;; (remove-hook 'text-mode-hook #'turn-on-auto-fill)
;; (add-hook 'org-mode-hook #'turn-off-auto-fill)
;; (add-hook 'text-mode-hook #'turn-off-auto-fill)
;; (add-hook 'org-roam-mode-hook #'turn-off-auto-fill)
#+end_src

これによって折り返しの限界を80から99999にすることにして回避する. 

#+begin_src emacs-lisp :tangle yes
(setq-default fill-column 99999)
(setq fill-column 99999)
#+end_src

これにより折り返しで / や $ 記号が表示される. 以下の設定で消す. 

#+begin_src emacs-lisp :tangle yes
;; / を削除
(set-display-table-slot standard-display-table 'wrap ?\ )
;; $ を削除
(set-display-table-slot standard-display-table 0 ?\ )
#+end_src

さらに折り返しの次のラインにインデントが挿入される. これはelectric-indent-modeの仕業. 現在org-modeのみで無効中. 

折り返しoff/onは, M-x toggle-truncate-linesで切り替えることができる. 

** visual-line-mode

単語単位での折り返しをするEmacs標準実装のモード. 

Emacsはウィンドウの右端の近くの単語の境界で折り返すよう試みる. これは単語の途中で折り返さないことにより可読性を高めるため. 

https://ayatakesi.github.io/emacs/25.1/Visual-Line-Mode.html

この設定はスクリーンの幅によって判定されるためたとえば文字列80で折り返すとかではない. 

日本語と英語が入り交じるときの解釈が変なので以下を設定した. 

#+begin_src emacs-lisp :tangle yes
(setq word-wrap-by-category t)
#+end_src

ref: [[https://www.reddit.com/r/emacs/comments/ov2s2r/wordwrap_problem_with_chinese_or_japanese/h76ipjy/][Word-wrap problem with Chinese or Japanese characters : emacs]]

** visual-fill-column

Doomだといらないかもだけど. 

#+begin_src emacs-lisp :tangle yes
;; (add-hook! visual-line-mode 'visual-fill-column-mode)
#+end_src

-> perfect-marginとの相性が悪い気がするのでいったん無効. 

- ref.
  -  [[http://sleepboy-zzz.blogspot.com/2015/12/emacs-visual-fill-columnel_29.html][memo: Emacs の visual-fill-column.el が便利だった]]

** perfect-margin

いい感じにmarginをとってくれる (https://github.com/mpwang/perfect-margin)

#+begin_src emacs-lisp :tangle yes
(use-package! perfect-margin
  :config
  (perfect-margin-mode t)
  ;; disable special window
  (setq perfect-margin-ignore-regexps '("*vterm*"))
  (setq perfect-margin-ignore-filters nil)  ;; disable minibuffer
)
#+end_src

** ターミナルの縦分割線をUTF-8できれいに描く

ref: [[https://www.reddit.com/r/emacs/comments/3u0d0u/how_do_i_make_the_vertical_window_divider_more/][How do I make the vertical window divider more pretty? : emacs]]

#+begin_src emacs-lisp :tangle yes
(unless (display-graphic-p)
  ;; ターミナルの縦分割線をUTF-8できれいに描く
  (defun my-change-window-divider ()
    (interactive)
    (let ((display-table (or buffer-display-table
           standard-display-table
           (make-display-table))))
      (set-display-table-slot display-table 5 ?│)
      (set-window-display-table (selected-window) display-table)))
  (add-hook 'window-configuration-change-hook 'my-change-window-divider))
#+end_src

** whitespace

余分な空白/タブに色づけ.

#+begin_src emacs-lisp :tangle yes
(use-package! whitespace
  :config
  ;; limit lie length -> display-fill-column-indicator-modeを使うためマスク. 
  ;; (setq whitespace-line-column 80) 
  (setq whitespace-style '(face 
                           ;;lines-tail
                           ))
  ;; 全角スペースを可視化
  (setq whitespace-space-regexp "\\(\u3000+\\)")
  (global-whitespace-mode 1))
#+end_src

** display-fill-column-indicator-mode

Emacsの画面に1行80文字のところに線を薄く引く.

プログラミングの世界では昔から80 columns ruleがあり, Emacsで80文字目を表示する機能もいろいろあったものの, Emacs 27.0.90からdefault機能として提供されるようになった.

(最も80(charは昔の話で, 最近のディスプレイの大きさだと100charがいいという議論もある).

今つかっているモニタで縦に３分割すると74がちょうどいいことがわかった. (先頭に行番号表示4char+1charのmarginあり). 

#+begin_src emacs-lisp :tangle yes
(setq-default display-fill-column-indicator-column 78)
(global-display-fill-column-indicator-mode)
#+end_src

** iedit

複数同時編集. 

なおDoom Emacsだと +company/completeとC-;のkeybind競合.

#+begin_src emacs-lisp :tangle yes
(use-package! iedit
  :bind
  ("C-;" . iedit-mode))
#+end_src

** bm

現在行のブックマークライブラリ. 

[[https://github.com/joodland/bm][GitHub - joodland/bm: bm.el -- Visual Bookmarks for GNU Emacs]]

しかし別用途とした現在行をハイライトしてログ解析とかでつかう. 

#+begin_src emacs-lisp :tangle yes
(use-package! bm
  :bind   (("<f5>" . bm-toggle))
  :config
  (setq temporary-bookmark-p t)
  (setq bm-face '((t (:background "steel blue" :foreground "#272822")))))
;;(setq bm-face '((t (:background "#525252" :foreground ""))))
;;	   ("<C-f5>"  . bm-next)
;;	   ("<S-f5>" . bm-previous))
#+end_src

** atomic-chrome

#+begin_src emacs-lisp :tangle yes
(use-package! atomic-chrome
  ;; auto generated by gpt4
  ;; :init
  ;; (setq atomic-chrome-default-major-mode 'markdown-mode
  ;;       atomic-chrome-buffer-open-style 'frame
  ;;       atomic-chrome-url-major-mode-alist
  ;;       '(("github\\.com" . gfm-mode)
  ;;         ("redmine\\." . textile-mode)))
  :config
  (setq atomic-chrome-buffer-open-style 'full)
  (atomic-chrome-start-server))
#+end_src

* Emacs

#+begin_src emacs-lisp :tangle yes
;; Emacs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Emacs29
(pixel-scroll-precision-mode)

;; doomだとhelpが割り当てられていたがdoomのhelpはF1をつかう.

(global-set-key (kbd "C-h") 'backward-delete-char)
(global-set-key (kbd "C-c h r") 'doom/reload)

;; Emacs起動時にいちいち質問されるのはうざい.
;; default tではなぜか無視できないので:allを設定しておく.
(setq enable-local-variables :all)

;;; 右から左に読む言語に対応させないことで描画高速化
(setq-default bidi-display-reordering nil)
#+end_src

** Copy file path with line

ファイルパスと行番号をコピーする。Claude Codeでのコード参照形式（file_path:line_number）に対応。

- +default/yank-buffer-path

#+begin_src emacs-lisp :tangle yes
(defun my/copy-file-path-with-line ()
  "Copy the current buffer's file path with line number."
  (interactive)
  (let ((path-with-line
         (concat (buffer-file-name) ":" (number-to-string (line-number-at-pos)))))
    (kill-new path-with-line)
    (message "%s" path-with-line)))

(map! :leader
      :desc "Copy file path with line"
      "f Y" #'my/copy-file-path-with-line)
#+end_src

** recentf

けっこうrecentfでハングすることが多いので少なくする. 

#+begin_src emacs-lisp :tangle yes
;; recentfに保存する数. 
(setq recentf-max-saved-items 300)
#+end_src

** Emacs ガーベジコレクション

ガーベジコレクションでEmacsのつかうメモリを最適化する. 

ガーベジコレクションが走る間隔が多ければ途中で重くなるが, 低スペックPCだとガーベジコレクションをこまめに走らせることで全体的に軽くすることも. 要調整. 

#+begin_src emacs-lisp :tangle yes
;; GCを減らして軽くする.
;; (setq gc-cons-threshold (* gc-cons-threshold 10))
;; GCの上限閾値をあえて下げる(低スペックPC)
;; (setq gc-cons-threshold (/ gc-cons-threshold 10))

;; どうもDoom だとデフォルトで大きな値が設定されている模様なので戻す. 
;; (setq gc-cons-percentage 0.1)
;; (setq gc-cons-threshold 800000)
;; GC実行のメッセージを出す
(setq garbage-collection-messages nil)
#+end_src

** ace-window

3つ以上のwindowの選択が番号でできる. defaultでC-x oを上書きしてる? C-u C-x o だとwindowをswapできる(ace-swap-window).

** undo-tree

ビジュアライズされたundoを提供. 

C-x uでvisualizerのバッファを開く. qで終了. 

** Helpful

Emacsの*Help Bufferを強化する. 

https://github.com/Wilfred/helpful

#+begin_src emacs-lisp :tangle no
(use-package! helpful
  :config
  (global-set-key (kbd "C-c C-d") #'helpful-at-point))
#+end_src

* Email
#+begin_src emacs-lisp :tangle yes
;; Email
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#+end_src

* Input

#+begin_src emacs-lisp :tangle yes
;; Input
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(set-language-environment "Japanese")
(prefer-coding-system 'utf-8)
(set-default 'buffer-filecoding-system 'utf-8)

;; migemo
(use-package! migemo
  :config
  (setq migemo-command "cmigemo")
  (setq migemo-options '("-q" "--emacs" "-i" "\a"))
  (setq migemo-dictionary "/usr/share/migemo/utf-8/migemo-dict")
  (setq migemo-user-dictionary nil)
  (setq migemo-regex-dictionary nil)
  (setq migemo-coding-system 'utf-8-unix)
  (migemo-init))
#+end_src

** fcitx

aggressive-setupでのminibuffer でのfcitx自動disableはよい. 相性が悪いのか, しばしば日本語入力とminibufferでEmacsがハングするので. 

#+begin_src emacs-lisp :tangle yes
(use-package! fcitx
  :config
  (setq fcitx-remote-command "fcitx5-remote")
  (fcitx-aggressive-setup)
  ;; Linux なら t が推奨されるものの、fcitx5 には未対応なためここは nil
  (setq fcitx-use-dbus nil))
#+end_src

** artist mode

[[https://www.emacswiki.org/emacs/ArtistMode][EmacsWiki: Artist Mode]]

Emacs上でカーソルやマウスを使って線が書ける.

- M-x artist-modeで起動. 
- C-c C-c で終了.
- defaultでは *.* を描写, Shiftで *-* になる.

昔なんちゃってelispを書いたけど, なんだdefaultであったのか.

ref: [[https://futurismo.biz/archives/1972/][秀丸のような罫線マクロないかなと思ってelisp作成した | Futurismo]]

* Lang

編集補助の中でも特にコーディング支援をまとめる.

** Generals

言語に依存しないコーディング支援ツール. 

*** smartparens

https://github.com/Fuco1/smartparens

Emacsでカッコの対応を取りつつ編集をするminor-mode. pareditを新しくrewriteした.

refs:

- https://ebzzry.com/en/emacs-pairs/
- http://kimi.im/2021-11-27-sexp-operations-in-emacs

[[https://github.com/hlissner/doom-emacs/blob/master/modules/config/default/%2Bemacs-bindings.el][doom emacsのsmartparens定義]]. +bindings +smartparensで有効.

#+begin_src emacs-lisp :tangle no
;;; smartparens
(:after smartparens
  :map smartparens-mode-map
  "C-M-a"           #'sp-beginning-of-sexp
  "C-M-e"           #'sp-end-of-sexp
  "C-M-f"           #'sp-forward-sexp
  "C-M-b"           #'sp-backward-sexp
  "C-M-n"           #'sp-next-sexp
  "C-M-p"           #'sp-previous-sexp
  "C-M-u"           #'sp-up-sexp
  "C-M-d"           #'sp-down-sexp
  "C-M-k"           #'sp-kill-sexp
  "C-M-t"           #'sp-transpose-sexp
  "C-M-<backspace>" #'sp-splice-sexp)
#+end_src

足りないのは自分で定義する必要あり. というかいろいろ再定義するか...

#+begin_src emacs-lisp :tangle yes
(use-package! smartparens-config
  :bind
  ("C-<right>" . sp-forward-slurp-sexp)
  ("M-<right>" . sp-forward-barf-sexp)
  ("C-<left>"  . sp-backward-slurp-sexp)
  ("M-<left>"  . sp-backward-barf-sexp)
  ("C-M-w" . sp-copy-sexp)
  ("M-[" . sp-backward-unwrap-sexp)
  ("M-]" . sp-unwrap-sexp)
  :config
  ;; copilot.elをいれたら相性が悪くなった.. 
  ;; (add-hook! 'clojure-mode-hook 'smartparens-strict-mode)
  (setq smartparens-strict-mode nil))

#+end_src

*** symbol-overlay

シンボルのハイライトをキー入力で制御できる.

https://github.com/wolray/symbol-overlay/

使ってないし companyとkeybindがかぶったのでいったん封印.

#+begin_src emacs-lisp :tangle no
(use-package! symbol-overlay
  :config
  (global-set-key (kbd "M-i") 'symbol-overlay-put)
  (global-set-key (kbd "M-n") 'symbol-overlay-switch-forward)
  (global-set-key (kbd "M-p") 'symbol-overlay-switch-backward)
  (global-set-key (kbd "<f7>") 'symbol-overlay-mode)
  (global-set-key (kbd "<f8>") 'symbol-overlay-remove-all))
#+end_src

*** codic

よい変数名を教えてくれるwebサービスcodicクライアント. 

[[https://codic.jp/][codic - プログラマーのためのネーミング辞書]]

- M-x codic: 英語 => 日本語
- M-x codic-translate => 日本語 => 英語(要token)

codic-translateを使うにはtokenを codic-api-tokenに設定する必要がある. 
現状は"private/config.el"に書いて読み込んでいる. 

#+begin_src emacs-lisp :tangle yes
(use-package! codic)
#+end_src

- [[https://github.com/emacsorphanage/codic][codic - GitHub]]
- [[https://futurismo.biz/archives/2538/][英語力を向上させたいのでまずは Emacs からはじめた | Futurismo]]

** Clojure

ref: [[https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/clojure/README.org][doom-emacs/README.org - GitHub]]

とりあえず，doomのclojureモジュール有効.

+ cider
+ clj-refactor
+ flycheck-clj-kondo

その他，

+ rainbow-delimiters, smartparensはdoomのcoreパッケージとしてすでにはいっている.
+ pereditはciderの中に入っている.

#+begin_src emacs-lisp :tangle yes
;; やりすぎindent mode
(add-hook! 'clojure-mode-hook 'aggressive-indent-mode)
;; 自動でalign整形.
(setq clojure-align-forms-automatically t)

(use-package! cider
  :bind
  ;; desing journal用にbinding追加
  ("C-c C-v C-p" . cider-pprint-eval-defun-to-comment)
  ("C-c C-v M-p" . cider-pprint-eval-last-sexp-to-comment)
  :config
  ;; connectとともにREPL bufferを表示.
  (setq  cider-repl-pop-to-buffer-on-connect t)
  ;; replに 出力しすぎてEmacsがハングするのを防ぐ.
  ;; 基本的にREPLへのprintは非効率なので cider inspect推奨. 
  ;; https://github.com/practicalli/spacemacs.d/issues/4
  (setq  cider-repl-buffer-size-limit 50)


  ;; companyでのあいまい補完.
  (add-hook 'cider-repl-mode-hook #'cider-company-enable-fuzzy-completion)
  (add-hook 'cider-mode-hook #'cider-company-enable-fuzzy-completion)

  ;; うまくうごかないな.. 
  (setq cider-special-mode-truncate-lines nil)
  ;; (add-hook 'cider-stacktrace-mode-hook (lambda () (setq truncate-lines nil)))
  ;; (add-hook 'cider-inspector-mode-hook (lambda () (setq truncate-lines nil)))

  ;; stack-frame表示をプロジェクトに限定
  (setq cider-stacktrace-default-filters '(project))

  ;; cider-connectで固定portを選択候補に表示.
  ;; 固定port自体は tools.depsからのnrepl起動時optionで指定.
  (setq cider-known-endpoints '(("kotori" "0.0.0.0" "34331")))
)
#+end_src

*** clj-refactor

Emacs CIDERでClojureを書くための便利なファクタツール提供.

https://github.com/clojure-emacs/clj-refactor.el

#+begin_src emacs-lisp :tangle yes
(add-hook! clojure-mode
  (clj-refactor-mode 1)
  (yas-minor-mode 1) ; for adding require/use/import statements
  ;; This choice of keybinding leaves cider-macroexpand-1 unbound
  (cljr-add-keybindings-with-prefix "C-c C-m")

  ;; cljr-rename-symbolでのプロンプト抑止. 
  ;; どうも初回実行が遅く２回目からは問題ない. 
  (setq cljr-warn-on-eval nil)
)
#+end_src

- cljr-clean-ns
  - namespaceを整理, cljr-project-cleanでプロジェクト全体に適用.
- cljr-rename-symbol 
  - シンボル(関数名や変数名含む). 
  - どうも遅いのてLSPのほうがここはいいのかも. 

*** cljstyle: formatter for Clojure

ref: [[https://qiita.com/lagenorhynque/items/a5d83b4a36a1cf1cacbe][GitHub]]

Doom Emascの editor/format moduleと連携可能.
Clojureだとdefaultが node-cljfmtなのでcljstyleを使うには設定が必要.

#+begin_src emacs-lisp :tangle yes
(add-hook! clojure-mode
  (set-formatter! 'cljstyle "cljstyle pipe" :modes '(clojure-mode))
  (add-hook 'before-save-hook 'format-all-buffer t t))
#+end_src

*** clj-kondo: linter for Clojure

ref: [[https://qiita.com/lagenorhynque/items/dd9d6a1d97cbea738bc0][GitHub]]

*** portal

Data Visualization for Clojure.

ref. https://github.com/djblue/portal

#+begin_src emacs-lisp :tangle yes
(defun portal.api/open ()
  (interactive)
  (cider-nrepl-sync-request:eval
   "(require 'portal.api) (portal.api/tap) (portal.api/open)"))

(defun portal.api/clear ()
  (interactive)
  (cider-nrepl-sync-request:eval "(portal.api/clear)"))

(defun portal.api/close ()
  (interactive)
  (cider-nrepl-sync-request:eval "(portal.api/close)"))
#+end_src

*** vega-view

#+begin_src emacs-lisp :tangle no
(use-package! vega-view
 :config
 (define-key clojure-mode-map (kbd "C-c M-n v") 'vega-view))
#+end_src

*** clerk

https://github.com/nextjournal/clerk

#+begin_src emacs-lisp :tangle no
(defun clerk-show ()
  (interactive)
  (when-let
      ((filename
        (buffer-file-name)))
    (save-buffer)
    (cider-interactive-eval
     (concat "(nextjournal.clerk/show! \"" filename "\")"))))
(define-key clojure-mode-map (kbd "<M-return>") 'clerk-show)
#+end_src

** Rust

#+begin_src emacs-lisp :tangle yes
(setq exec-path (append exec-path '("~/.cargo/bin")))
#+end_src

** rest

#+begin_src emacs-lisp :tangle no
(use-package! restclient
  :mode (("\\.rest\\'" . restclient-mode)
         ("\\.restclient\\'" . restclient-mode)))
(use-package! ob-restclient
  :after org restclient
  :init
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((restclient . t))))
#+end_src


** mermaid-mode

https://github.com/abrochard/mermaid-mode

#+begin_src emacs-lisp :tangle yes
(use-package! mermaid-mode)
#+end_src

mermaid-open-browser(C-c C-o)でmermaid-jsのサイトに飛んで表示できる. 

https://mermaid-js.github.io/mermaid-live-editor

ローカルで表を生成するにはmermaid-cliのインストールが別途必要. 

* Os

#+begin_src emacs-lisp :tangle yes
;; OS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src

** EXWM

EmacsのWindow Manager.

もはやこれをつかうと世界がEmacsになりEmacs 引きこもり生活が完成する.

counsel-linux-appだと起動時にハングしてPC再起動になることが多い. Shift+Alt+&によるアプリケーション起動がいいかも. 

#+begin_src emacs-lisp :tangle yes
(use-package! exwm
  :if (not (wsl-p))
  :after counsel
  :init
  (setq counsel-linux-app-format-function
        #'counsel-linux-app-format-function-name-only)
  (map!
        :leader
        :prefix ("z" . "exwm")
        "c" #'exwm-reset
        "o" (lambda (command)
                         (interactive (list (read-shell-command "$ ")))
                         (start-process-shell-command command nil command))
        "z" #'exwm-workspace-switch
        "m" #'exwm-workspace-move-window
        "a" #'counsel-linux-app
        "s" #'counsel-search  ;; open chrome and search
        )
  (add-hook 'exwm-input--input-mode-change-hook
            'force-mode-line-update)
  (add-hook 'exwm-update-class-hook
            (lambda ()
              (exwm-workspace-rename-buffer exwm-class-name)))
  ;; どうもChromeを立ち上げるとハングするので無効にしておく.
  (winner-mode -1)

  :config
  (require 'exwm-randr)
  (setq exwm-randr-workspace-output-plist '(0 "HDMI-1"))
  (add-hook
   'exwm-randr-screen-change-hook
   (lambda ()
     (start-process-shell-command
      "xrandr" nil "xrandr --output HDMI-1 --primary --right-of eDP-1 --auto")))
  (exwm-randr-enable)

  (require 'exwm-systemtray)
  (exwm-systemtray-enable)

  ;; edit-server的な. C-c 'で編集できるのでよりbetter
  ;; 一度入力したものを再度開くと文字化けする.
  (require 'exwm-edit)
  (setq exwm-edit-split t)

  (setf epg-pinentry-mode 'loopback)
  (defun pinentry-emacs (desc prompt ok error)
    (let ((str (read-passwd
                (concat (replace-regexp-in-string
                         "%22" "\""
                         (replace-regexp-in-string
                          "%0A" "\n" desc)) prompt ": "))))
      str))

  ;; from https://github.com/ch11ng/exwm/wiki/Configuration-Example
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (fringe-mode 1)

  ;; google-chromeを起動するとmouse on menu-barがpopupしてハングする対策
  ;; https://stackoverflow.com/questions/17280845/emacs-disable-pop-up-menus-on-mouse-clicks
  (fset 'menu-bar-open nil)
  (fset 'x-menu-bar-open nil)

  ;; Turn on `display-time-mode' if you don't use an external bar.
  (setq display-time-default-load-average nil)
  (display-time-mode t)
  (display-battery-mode 1)

  (setq exwm-workspace-number 2)

  (setq exwm-input-simulation-keys
        '(([?\C-b] . [left])
          ;; Chromeページ内検索のために空ける          
          ;; ([?\C-f] . [right])
          ;; 2022.03.23 やっぱり解除. どうもC-fがスムーズな操作を阻害する.
          ;; ページ内検索はSurfingkeysというExtensionを利用(/).
          ([?\C-f] . [right])
          ([?\C-p] . [up])
          ([?\C-n] . [down])
          ([?\C-a] . [home])
          ([?\C-e] . [end])
          ([?\M-v] . [prior])
          ([?\C-v] . [next])
          ([?\C-d] . [delete])
          ([?\C-m] . [return])
          ([?\C-h] . [backspace])
          ([?\C-k] . [S-end delete])))

  (exwm-enable))
#+end_src

* Org-mode


ご存知！

- [[https://github.com/tsu-nera/dotfiles/blob/master/.emacs.d/inits/50_org-mode.org][dotfiles/50_org-mode.org at master · tsu-nera/dotfiles · GitHub]]
  - 昔の設定. すこしずつ移植したい.

** ファイルパス

ファイルパス関連の定義はまとめてここで実施.

#+begin_src emacs-lisp :tangle yes
(after! org
  (setq org-directory (file-truename "~/repo/gtd"))

  (defconst my/gtd-projects-file (concat org-directory "/home.org"))
  (defconst my/inbox-file
    (concat org-directory "/inbox/inbox.org"))
  (defconst my/daily-journal-dir
    (concat org-directory "/journals/daily"))
  (defconst my/weekly-journal-dir
    (concat org-directory "/journals/weekly"))
  (defconst my/project-journal-bakuchi
    (file-truename "~/repo/bakuchi-doc/notes/journal.org"))
  (defconst my/project-journal-deepwork
    (file-truename "~/repo/keido/notes/zk/journal_deepwork.org"))

  ;; org-captureのtargetは詳しくいろいろ設定するのでdefaultは不要.
  ;; (setq org-default-notes-file "gtd/gtd_projects.org")

  ;; 何でもかんでも agenda すると思いので厳選.
  ;; org-journalの機能でこのほかに今日のjournal fileが追加される.
  (setq org-agenda-files
        (list
         ;; my/project-journal-bakuchi
         ;; my/project-journal-deepwork
         ;; my/daily-journal-dir
         my/gtd-projects-file
         )))

(defun my/create-weekly-org-file (path)
  (expand-file-name (format "%s.org" (format-time-string "%Y-w%V")) path))
(defun my/create-daily-org-file (path)
  (expand-file-name (format "%s.org" (format-time-string "%Y-%m-%d")) path))

(defconst my/weekly-journal-dir "~/repo/keido/notes/zk")

(defconst my/weekly-private-dir "~/repo/gtd/journals/weekly")
(defconst my/daily-private-dir "~/repo/gtd/journals/daily")
#+end_src

** Basics

#+begin_src emacs-lisp :tangle yes
;; Org mode
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; スマホとの共有のため, github を clone したものを Dropbox に置いて$HOME に symlink している.
(after! org

  (setq org-return-follows-link t) ;; Enter でリンク先へジャンプ
  (setq org-use-speed-commands t)  ;; bullet にカーソルがあると高速移動
  (setq org-hide-emphasis-markers t) ;; * を消して表示.
  (setq org-pretty-entities t)

  ;; カレンダー表示を英語表記へ
  (setq system-time-locale "C") 

  ;; defaultではFootnotes
  (setq org-footnote-section "Footnotes")
  (setq org-footnote-auto-adjust t)
  (setq org-indent-indentation-per-level 1) ;; indent波浅く

  ;; M-RET の挙動の調整
  ;; t だと subtree の最終行に heading を挿入
  ;; nil だと current point に挿入
  ;; なお，C-RET だと subtree の最終行に挿入され
  ;; C-S-RET だと手前に挿入される.
  (setq org-insert-heading-respect-content nil)

  (setq org-startup-indented t)
  (setq org-indent-mode-turns-on-hiding-stars nil)

  (setq org-startup-folded 'showall) ;; 見出しの階層指定
  (setq org-startup-truncated nil) ;; 長い文は折り返す.

  ;; electric-indent は org-mode で誤作動の可能性があることのこと
  ;; たまにいきなり org-mode の tree 構造が壊れる.とりあえず設定しておく
  ;; この設定の効果が以下の記事で gif である.
  ;; https://www.philnewton.net/blog/electric-indent-with-org-mode/
  (add-hook! org-mode (electric-indent-local-mode -1)))
#+end_src

** org-agenda

#+begin_src emacs-lisp :tangle yes
(after! org
  ;; org-agenda
  (setq org-refile-targets '((org-agenda-files :maxlevel . 3)))
  ;; 時間表示が 1 桁の時, 0 をつける
  (setq org-agenda-time-leading-zero t) 
  (setq calendar-holidays nil) ;; 祝日を利用しない.
  (setq org-log-done 'time);; 変更時の終了時刻記録.

  ;; スケジュールやデッドラインアイテムは DONE になっていれば表示する
  (setq org-agenda-skip-deadline-if-done nil)
  (setq org-agenda-skip-scheduled-if-done nil)

  ;; inactive timestamp [] を非表示.
  (setq org-agenda-include-inactive-timestamps nil)
  ;; default で 時間を表示
  (setq org-agenda-start-with-log-mode t) 

  ;; org-agenda speedup tips
  ;; https://orgmode.org/worg/agenda-optimization.html

  (setq org-agenda-file-regexp "\\`\\\([^.].*\\.org\\\|[0-9]\\\{8\\\}\\\(\\.gpg\\\)?\\\)\\'")

  ;; 期間を限定
  (setq org-agenda-span 14)
  ;; Inhibit the dimming of blocked tasks:
  (setq org-agenda-dim-blocked-tasks nil)
  ;; Inhibit agenda files startup options:memo
  (setq org-agenda-inhibit-startup nil)
  ;; Disable tag inheritance in agenda:
  (setq org-agenda-use-tag-inheritance nil)

  ;; https://emacs.stackexchange.com/questions/13237/in-org-mode-how-to-view-todo-items-for-current-buffer-only
  (defun org-todo-list-current-file (&optional arg)
    "Like `org-todo-list', but using only the current buffer's file."
    (interactive "P")
    (let ((org-agenda-files (list (buffer-file-name (current-buffer)))))
      (if (null (car org-agenda-files))
        (error "%s is not visiting a file" (buffer-name (current-buffer)))
        (org-todo-list arg))))
)
#+end_src

** TODOキーワード拡張

TODOキーワードのカスタマイズ. M-x C-c t.

ref. [[https://orgmode.org/manual/TODO-Extensions.html][TODO Extensions (The Org Manual)]]

#+begin_src emacs-lisp :tangle yes
(setq org-todo-keywords
      '((sequence "📊(a)" "💡(b)" "✅(c)" "👨(d)" "🔬(e)" "👩(f)" "🎨(g)" "|")
        (sequence "📂(h)" "✨(i)" "🔌(k)" "🔗(l)" "📝(m)" "🌳(n)" "|")
        (sequence "🪨(o)" "🧩(p)" "📜(q)" "📍(r)" "🔍(s)" "🔦(t)" "|")
        (sequence "🔧(w)" "🌱(z)" "|")))
#+end_src

** org-capture

[[https://orgmode.org/manual/Capture-templates.html][Capture templates (The Org Manual)]]

#+begin_src emacs-lisp :tangle yes
(after! org
  (setq org-capture-templates
        '(("i" "📥 Inbox" entry
           (file my/inbox-file) 
           "* %?\nCaptured On: %U\n"
           :klll-buffer t)
          ("I" "📥+🌐 Inbox+Browser" entry
           (file my/inbox-file)
           "* %?\nSource: [[%:link][%:description]]\nCaptured On: %U\n"
           :klll-buffer t)
          ("q" "📥+🌐 Inbox+Browser(quote)" entry
           (file my/inbox-file)
           "* %?\nSource: [[%:link][%:description]]\nCaptured On: %U\n%i\n"
           :klll-buffer t))))
#+end_src

*** capture to daily journal

#+begin_src emacs-lisp :tangle yes
;; 現状つかってないのでマスク
;; (defun my/create-timestamped-org-file (path)
;;   (expand-file-name (format "%s.org" (format-time-string "%Y%m%d%H%M%S")) path))

(after! org
  (setq org-capture-templates
        (append 
          '(("c" "☑ Planning" plain
             (file+headline
              (lambda () 
                (my/create-weekly-org-file my/weekly-private-dir))
              "Planning")
             "%?"
             :unnarrowed t
             :kill-buffer t)
            ("t" "🤔 Thought" entry
             (file+headline
              (lambda () 
                (my/create-weekly-org-file my/weekly-private-dir))
              "Thoughts")
             "* 🤔 %?\n%T"
             :empty-lines 1
             :unnarrowed t
             :kill-buffer t)
            ("T" "🤔+📃 Thought+Ref" entry
             (file+headline
              (lambda () 
                (my/create-weekly-org-file my/weekly-private-dir))
              "Thoughts")
             "* 🤔 %?\n%T from %a\n"
             :empty-lines 1
             :unnarrowed t
             :kill-buffer t)
            ("l" "🤔+🌐 Thought+Browser" entry
             (file+headline
              (lambda () 
                (my/create-weekly-org-file my/weekly-private-dir))
              "Thoughts")
             "* 🤔 %?\n%T from [[%:link][%:description]]\n"
             :empty-lines 1
             :unnarrowed t
             :kill-buffer t)
            ("p" "🍅 Pomodoro" entry
             (file+headline
              (lambda () 
                (my/create-weekly-org-file my/weekly-private-dir))
              "DeepWork")
             "* 🍅 %?\n%T"
             :empty-lines 1
             :unnarrowed t
             :kill-buffer t)
            ("r" "🧘 Recovery" entry
             (file+headline
              (lambda () 
                (my/create-weekly-org-file my/weekly-private-dir))
              "Recovery")
             "* 🧘 %?\n%T"
             :empty-lines 1
             :unnarrowed t
             :kill-buffer t)
            ("j" "🖊 Journal" plain
             (file 
              (lambda ()
                (my/create-weekly-org-file my/weekly-private-dir)))
             "%?"
             :empty-lines 1
             :unnarrowed t
             :kill-buffer t)
            ("J" "🖊+📃 Journal+Ref" plain
             (file 
              (lambda ()
                (my/create-weekly-org-file my/weekly-private-dir)))
             "%?\n%a"
             :empty-lines 1
             :unnarrowed t
             :kill-buffer t)
            ("L" "🖊+🌐 Journal+Browser" plain
             (file 
              (lambda ()
                (my/create-weekly-org-file my/weekly-private-dir)))
             "%?\nSource: [[%:link][%:description]]\nCaptured On: %U\n"
             :empty-lines 1
             :unnrrowed t
             :kill-buffer t)) org-capture-templates)))
#+end_src

*** capture to project journal

#+begin_src emacs-lisp :tangle yes
(after! org
  (setq org-capture-templates
        (append 
        '(("b" "🖊 bakuchi entry" entry
           (file+olp+datetree my/project-journal-bakuchi)
           "* %?\nCaptured On: %T\n"
           :unnarrowed t
           :empty-lines 1
           :tree-type week
           :klll-buffer t)
          ("B" "🖊+✍ bakuchi append" plain
           (file my/project-journal-bakuchi)
           "%?"
           :empty-lines 1
           :unnarrowed t
           :jump-to-captured t
           :kill-buffer t)
          ("d" "🖊 DeepWork entry" entry
           (file+olp+datetree my/project-journal-deepwork)
           "* %?\nCaptured On: %T\n"
           :unnarrowed t
           :empty-lines 1
           :tree-type week
           :klll-buffer t)) org-capture-templates)))
#+end_src

*** Google Chrome Extention: Org Capture

Google Chromeにを入れることでWeb Pageがorg-captureと連携([[https://chrome.google.com/webstore/detail/org-capture/kkkjlfejijcjgjllecmnejhogpbcigdc?hl=ja][link]]).

ChromeでCtrl + Shift + Lで起動.

** org-export(ox)

Org-modeのファイルをエクスポートする機能. ox package.

サブパッケージが数多くあるが, ここでは共通情報まとめ.

org-export-with-xxxという設定項目でいろいろ制御できる.

[[https://orgmode.org/manual/Export-Settings.html][Export Settings (The Org Manual)]]

しかし, 以下が自動的に変換されてしまう...この文字に対する制御方法が見つからない...

- > &gt; 
- < &lt;
- & &amp;

どうもHTML tagとかHTML Entitiesと呼ばれている(ref. [[https://orgmode.org/org.html#Headlines-in-HTML-export][The Org Manual]]).

#+begin_quote
The HTML export back-end transforms ‘<’ and ‘>’ to ‘&lt;’ and ‘&gt;’.
#+end_quote

ただox-html.elにはこういう設定がdefaultでされている. 他のexportへの移植が必要.

#+begin_src emacs-lisp :tangle no
(setq org-export-html-protect-char-alist
  '(("&" . "&amp;")
    ("<" . "&lt;")
    (">" . "&gt;"))
#+end_src

[[https://orgmode.org/manual/Advanced-Export-Configuration.html][Advanced Export Configuration (The Org Manual)]]

おそらく, exportをかけたあとにhook関数によって文字列変換が必要.

#+begin_src emacs-lisp :tangle yes
(after! ox
;; (setq org-export-async-init-file "/home/tsu-nera/.doom.d/async-init.el")

  (defun my/hugo-filter-html-amp (text backend info)
    (when (org-export-derived-backend-p backend 'hugo)
      (replace-regexp-in-string "&amp;" "&" text)))
  (defun my/hugo-filter-html-gt (text backend info)
    (when (org-export-derived-backend-p backend 'hugo)
      (replace-regexp-in-string "&gt;" ">" text)))
  (defun my/hugo-filter-html-lt (text backend info)
    (when (org-export-derived-backend-p backend 'hugo)
      (replace-regexp-in-string "&lt;" "<" text)))
  (add-to-list
   'org-export-filter-plain-text-functions 'my/hugo-filter-html-amp)
  (add-to-list
   'org-export-filter-plain-text-functions 'my/hugo-filter-html-gt)
  (add-to-list
   'org-export-filter-plain-text-functions 'my/hugo-filter-html-lt))
#+end_src

*** org-preview-html

今のEmacs, xwidget用にコンパイルしてなかったな...

ewwでプレビューできる.

#+begin_src emacs-lisp :tangle yes
(use-package! org-preview-html)
#+end_src

*** ox-hugo

Org-modeで書いたブログ記事をHugoにあったMarkdown形式に変換する.

ブログFuturismoはOrg-modeで執筆してこれを利用してMarkdownに変換している.

#+begin_src emacs-lisp :tangle yes
(use-package! ox-hugo
  :after ox
  :bind
  ;; org-roamのexportで多様するのでC-c rのprefixをつけておく.
  ("C-c r e" . org-hugo-export-to-md)
  :config

  (setq org-hugo-auto-set-lastmod t)
  ;; なんか.dir-locals.elに書いても反映してくれないな. 
  (setq org-export-with-author nil)
  ;; org-hugo-get-idを使うように設定.
  (setq org-hugo-anchor-functions 
        '(org-hugo-get-page-or-bundle-name
          org-hugo-get-custom-id
          org-hugo-get-id
          org-hugo-get-md5
          ;; 日本語に不向きな気がする
          ;; org-hugo-get-heading-slug
          ))
  ;; WebP画像の自動コピーを有効化
  (add-to-list 'org-hugo-external-file-extensions-allowed-for-copying "webp"))
#+end_src

このox-hugoで出力されるMarkdownはどうもリスト表示でスペースが4つ入ってしまう. GitHub Favorite Markdownのようにリストでのスペース２であって欲しいものの解決方法が見つからない.

*** ox-rst

Org-modeで書いたWiki用のページをSphinxで公開するためにreST形式に変換する.

リンク形式がうまく変換できないのでけっこう強引に変換している(もう少しうまく改善したい).

#+begin_src emacs-lisp :tangle yes
(use-package! ox-rst
  :after ox)

(after! ox
  (defun my/rst-to-sphinx-link-format (text backend info)
    (when (and (org-export-derived-backend-p backend 'rst)
               (not (search "<http" text)))
      (replace-regexp-in-string
       "\\(\\.org>`_\\)" ">`"
       (concat ":doc:" text) nil nil 1)))

  (add-to-list 'org-export-filter-link-functions
               'my/rst-to-sphinx-link-format))
#+end_src

*** ox-qmd

GitHub Flavored Markdown.

標準のMarkdownの出力だと見た目が悪い. Bufferに書き出してGitHubとかにコピペするとき用にいれておく.

ref. [[https://qiita.com/0x60df/items/3cde67967e3db30d9afe][Org-modeからQiita準拠のMarkdownをexportするパッケージを作ってみました - Qiita]]

#+begin_src emacs-lisp :tangle yes
(use-package! ox-qmd)
#+end_src

ox-gfmは2017からメンテされてないのでやめとくか([[https://github.com/larstvei/ox-gfm/issues/44][ref]]).

** org-babel(ob)

Org-modeのなかでLiterature Programming.

基本操作:

- C-c C-, コードブロックの挿入テンプレート呼び出し(org-insert-structure-tempate)
- C-c C-c コード実行(org-babel-execute-src-block)
- C-c C-o コード実行結果を開く(org-babel-open-src-block-result)
- C-c ' ソースコード編集(org-edit-src-code)
  - どうもEoom Emacsだと keybindingが外れいてる.
  - C-c l '(org-edit-special)で開く.

#+begin_src emacs-lisp :tangle yes
  (after! org
    ;; https://stackoverflow.com/questions/53469017/org-mode-source-editing-indents-code-after-exiting-source-code-block-editor
    ;; インデント. default 2になっているとへんな隙間が先頭に入る.
    (setq org-edit-src-content-indentation 0)
    (setq org-src-preserve-indentation t)
    ;; TABの挙動
    (setq org-src-tab-acts-natively t)

    ;; org-babel のソースをキレイに表示.
    (setq org-src-fontify-natively t)
    (setq org-fontify-whole-heading-line t)

    ;; 評価でいちいち質問されないように.
    (setq org-confirm-babel-evaluate nil)

    ;; org-babel で 実行した言語を書く. デフォルトでは emacs-lisp だけ.
    (org-babel-do-load-languages
      'org-babel-load-languages
      '((lisp . t)
	(shell . t)
	(clojure . t)))

    ;; org-modeからclojure codeを評価.
    (define-key org-mode-map (kbd "C-c C-v e") 'cider-eval-last-sexp)
    ;; (org-defkey org-mode-map "\C-u\C-x\C-e" 'cider-eval-last-sexp)

    ;; Clojure Modeの特別対応. keybindingが上書きされるので.
    ;; (define-key clojure-mode-map (kbd "C-c C-x k") 'org-edit-src-exit)
    ;; (define-key clojure-mode-map (kbd "C-c C-x q") 'org-edit-src-abort)
    )
#+end_src

refs:

- [[https://orgmode.org/manual/Key-bindings-and-Useful-Functions.html][org-babel Key bindings and Useful Functions (The Org Manual)]]
- [[https://misohena.jp/blog/2017-10-26-how-to-use-code-block-of-emacs-org-mode.html][org-modeのコードブロック(Babel)の使い方 | Misohena Blog]]

*** ob-html

[[https://misohena.jp/blog/2021-08-03-execute-html-in-org-mode-code-blocks.html][org-modeのコードブロックでHTMLを「実行」する | Misohena Blog]]

#+begin_src emacs-lisp :tangle yes
(use-package! ob-html
  :after org
  :config
  ;; C-c C-o でブラウザで開く.
  (org-babel-html-enable-open-src-block-result-temporary))
#+end_src

** org-superstar

org-superstar-mode(+pretty option)関連.

bulletをおしゃれにかえる. ただそれと引き換えにパフォーマンスはちょっと落ちるかも.

#+begin_src emacs-lisp :tangle no
(after! org
;;; Titles and Sections
;; hide #+TITLE:
;; (setq org-hidden-keywords '(title))
;; set basic title font
;; (set-face-attribute 'org-level-8 nil :weight 'bold :inherit 'default)
;; Low levels are unimportant => no scaling
;; (set-face-attribute 'org-level-7 nil :inherit 'org-level-8)
;; (set-face-attribute 'org-level-6 nil :inherit 'org-level-8)
;; (set-face-attribute 'org-level-5 nil :inherit 'org-level-8)
;; (set-face-attribute 'org-level-4 nil :inherit 'org-level-8)
;; Top ones get scaled the same as in LaTeX (\large, \Large, \LARGE)
;; (set-face-attribute 'org-level-3 nil :inherit 'org-level-8 :height 1.2) ;\large
;; (set-face-attribute 'org-level-2 nil :inherit 'org-level-8 :height 1.44) ;\Large
;; (set-face-attribute 'org-level-1 nil :inherit 'org-level-8 :height 1.728) ;\LARGE
;; Only use the first 4 styles and do not cycle.
(setq org-cycle-level-faces nil)

;; orgの階層の色分けレベル.
;; (setq org-n-level-faces 8)

;; Document Title, (\huge)
;; (set-face-attribute 'org-document-title nil
;;                    :height 2.074
;;                    :foreground 'unspecified
;;                    :inherit 'org-level-8)

;; (with-eval-after-load 'org-superstar
;;  (set-face-attribute 'org-superstar-item nil :height 1.2)
;;  (set-face-attribute 'org-superstar-header-bullet nil :height 1.2)
;;  (set-face-attribute 'org-superstar-leading nil :height 1.3))
;; Set different bullets, with one getting a terminal fallback.
(setq org-superstar-headline-bullets-list '("■" "◆" "●" "▷"))
;; (setq org-superstar-special-todo-items t)

;; Stop cycling bullets to emphasize hierarchy of headlines.
(setq org-superstar-cycle-headline-bullets nil)
;; Hide away leading stars on terminal.
;; (setq org-superstar-leading-fallback ?\s)
(setq inhibit-compacting-font-caches t))
#+end_src

** org-roam

Zettelkasten MethodのOrg-roam実装.

#+begin_src emacs-lisp :tangle yes
  ;; org-roam
  (setq org-roam-directory (file-truename "~/repo/keido/notes"))
  (setq org-roam-zk-dir (concat org-roam-directory "/zk"))
  (setq org-roam-db-location (file-truename "~/repo/keido/db/org-roam.db"))

  (use-package! org-roam
    :after org
    :init
    (setq org-roam-v2-ack t)
    (map!
          :leader
          :prefix ("r" . "org-roam")
          "f" #'org-roam-node-find
          "i" #'org-roam-node-insert
          "l" #'org-roam-buffer-toggle
          "t" #'org-roam-tag-add
          "T" #'org-roam-tag-remove
          "a" #'org-roam-alias-add
          "A" #'org-roam-alias-remove
          "r" #'org-roam-ref-add
          "R" #'org-roam-ref-remove
          "o" #'org-id-get-create
          "u" #'my/org-roam-update
          "D" #'org-roam-dailies-goto-today
          )
    :custom
    ;;ファイル名を ID にする.
    (org-roam-capture-templates
     '(("z" "🌱 Zettel" plain "%?"
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                           "\n#+date: %T\n#+title:🌱${title}\n#+filetags: :ZETTEL:\n")
        :unnarrowed t)
       ("w" "📝 Wiki" plain "%?"
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                           "#+title:📝${title}\n#+filetags: :WIKI:\n")
        :unnarrowed t)
       ("t" "🔖 Tag" plain "%?"
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                           "#+title:🔖${title}\n#+filetags: :TAG:\n")
        :unnarrowed t)
       ("h" "👨 Person" plain "%?"
        :target (file+head
                 "zk/%<%Y%m%d%H%M%S>.org"
                 "#+title:👨${title}\n#+filetags: :PERSON:\n")
        :unnarrowed t)
       ("f" "📂 Type" plain "%?"
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                           "#+title:📂${title}\n#+filetags: :TYPE:\n")
        :unnarrowed t)
       ("m" "🌳 MOC" plain "%?"
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                           "#+title:🌳${title}\n#+filetags: :MOC:\n")
        :unnarrowed t)
       ("i" "✅ Issue" plain "%?"
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                          "#+title:✅${title}\n#+filetags: :ISSUE:\n")
        :unnarrowed t)
       ("d" "💡 Idea" plain "%?"
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                           "#+title:💡${title}\n#+filetags: :IDEA:\n")
        :unnarrowed t)
       ("c" "📑 Concept" plain "%?"
        :target (file+head
                 "zk/%<%Y%m%d%H%M%S>.org"
                 "#+title:🎓${title}\n#+filetags: :CONCEPT:\n")
        :unnarrowed t)
       ("k" "🦊 Darkfox" plain "%?"
        :target (file+head
                 "zk/%<%Y%m%d%H%M%S>.org"
                 "#+title:🦊${title}\n#+filetags: :DARKFOX:\n")
        :unnarrowed t)
       ("b" "📚 Book" plain
        "%?

  - title: %^{title}
  - authors: %^{author}
  - date: %^{date}
  - publisher: %^{publisher}
  - url: http://www.amazon.co.jp/dp/%^{isbn}
  "
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                           "#+title:📚${title} - ${author}(${date})\n#+filetags: :BOOK:SOURCE:\n")
        :unnarrowed t)
       ("s" "🎙‍ Talk" plain
        "%?

  - title: %^{title}
  - url: %^{url}
  "
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                           "#+title:🎙 ${title} - ${editor}(${date})\n#+filetags: :TALK:SOURCE:\n")
        :unnarrowed t)
       ("o" "💻 Online" plain
        "%?

  - title: %^{title}
  - authors: %^{author}
  - url: %^{url}
  "
        :target (file+head "zk/%<%Y%m%d%H%M%S>.org"
                           "#+title:💻${title}\n#+filetags: :ONLINE:SOURCE:\n")
        :unnarrowed t)))
    (org-roam-extract-new-file-path "%<%Y%m%d%H%M%S>.org")
    ;;        :map org-mode-map
    ;;        ("C-M-i"    . completion-at-point)
    :config
    (defun my/org-roam-update ()
      (interactive)
      (org-id-update-id-locations)
      (org-roam-db-sync)
      (org-roam-update-org-id-locations))

    (setq org-roam-mode-sections
          '((org-roam-backlinks-section :unique t)))

    (setq org-roam-db-gc-threshold most-positive-fixnum)

    ;; for speed up
    ;; (setq org-roam-node-default-sort 'file-mtime)

    (setq +org-roam-open-buffer-on-find-file nil)
    ;; (org-roam-db-autosync-mode)
    (org-roam-db-autosync-enable)

    ;; (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))

    ;; for emacs 29~
    ;; (when (>= emacs-major-version 29)
    ;; (setq org-roam-database-connector 'sqlite-builtin))
  )
#+end_src

#+begin_src emacs-lisp :tangle yes
(setq org-roam-db-node-include-function
      (lambda ()
        (not (member "" (org-get-tags)))))
#+end_src

*** consult-org-roam(Org-roam検索強化)

ref. https://github.com/jgru/consult-org-roam

以下の機能を提供.ファイル名は今は日付にしているからいらないかな.全文検索は動かない.バックリンク検索だけ使えそう.

- ファイル名検索
- バックリンク検索
- 全文検索

#+begin_src emacs-lisp :tangle yes
(use-package! consult-org-roam
   :init
   (require 'consult-org-roam)
   ;; Activate the minor-mode
   (consult-org-roam-mode 1)
   :custom
   (consult-org-roam-grep-func #'consult-ripgrep)
   :config
   ;; Eventually suppress previewing for certain functions
   (consult-customize
    consult-org-roam-forward-links
    :preview-key (kbd "M-."))
   :bind
   ("C-c r F" . consult-org-roam-file-find)
   ("C-c r b" . consult-org-roam-backlinks)
   ("C-c r S" . consult-org-roam-search))
#+end_src

*** Org-roam管理下のノートの全文検索

[[https://org-roam.discourse.group/t/using-consult-ripgrep-with-org-roam-for-searching-notes/1226][Using consult-ripgrep with org-roam for searching notes - How To - Org-roam]]

consult-ripgrepを [[https://jblevins.org/projects/deft/][deft]] の代わりに使う. より高速.

検索対象が多すぎるとハングするので改善したい.

#+begin_src emacs-lisp :tangle yes
(defun my/org-roam-rg-search ()
  "Search org-roam directory using consult-ripgrep. With live-preview."
  (interactive)
  (consult-ripgrep org-roam-directory))
(global-set-key (kbd "C-c r s") 'my/org-roam-rg-search)
#+end_src

*** org-publish(Org-roamのノートをサイトへ公開)

hugo用. 現状exit abnormally で動かないので調べる.

#+begin_src emacs-lisp :tangle no
(setq org-publish-project-alist
      (list
       (list "keido-hugo"
             :recursive nil
             :base-directory org-roam-zk-dir
             :publishing-directory "~/repo/keido-hugo/content"
             :exclude ".*gitignore|.*/private/.*" 
             :publishing-function 'org-hugo-export-wim-to-md
             :with-author nil           ;; 作成者除外
             :with-creator nil          ;; EmacsとOrg version表記除外
             :with-toc nil                ;; Table of Contents出力
             :section-numbers nil       ;; ナンバリング禁止
             :time-stamp-file nil       ;; タイムスタンプを除外
             )))

;; (require 'org-roam-export)
#+end_src

html用.

#+begin_src emacs-lisp :tangle no
(setq org-publish-project-alist
      (list
       (list "keido-org"
             :recursive nil
             :base-directory org-roam-zk-dir
             :publishing-directory "~/repo/keido-org/public/notes"
             :exclude ".*gitignore|.*/private/.*" 
             ;; :auto-sitemap t
             ;; :sitemap-function 'roam-sitemap
             ;; :sitemap-title "Keido notes"
             :publishing-function 'org-html-publish-to-html
             :with-author nil           ;; 作成者除外
             :with-creator nil          ;; EmacsとOrg version表記除外
             :with-toc t                ;; Table of Contents出力
             :section-numbers nil       ;; ナンバリング禁止
             :time-stamp-file nil       ;; タイムスタンプを除外
             )))

(defun my/setup-org-theme (backend)
  (goto-char (point-max))
  (insert "\n#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup\n")
  (insert "\n#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>\n"))

(defun my/collect-backlinks-string (backend)
  "Insert backlinks into the end of the org file before parsing it."
  (when (org-roam-node-at-point)
    (goto-char (point-max))
    ;; Add a new header for the references
    (insert "\n\n* 🔗Backlinks\n")
    (let* ((backlinks (org-roam-backlinks-get (org-roam-node-at-point))))
      (dolist (backlink backlinks)
        (let* ((source-node (org-roam-backlink-source-node backlink))
               (node-file (org-roam-node-file source-node))
               (file-name (file-name-nondirectory node-file))
               (title (org-roam-node-title source-node)))
          (insert
           (format "- [[./%s][%s]]\n" file-name title)))))))

(add-hook 'org-export-before-parsing-functions 'my/setup-org-theme)
(add-hook 'org-export-before-processing-functions 'my/collect-backlinks-string)

;; (require 'org-roam-export)
#+end_src

*** org-roam-dailies

Org-roamに組み込まれた劣化版org-journal. 現状使用するのをやめた.

org-roam-dialiesよりもorg-journalを利用する(org-agendaの都合).

ref. [[https://org-roam.discourse.group/t/org-journal-vs-org-roam-dailies/384][Org-journal vs org-roam-dailies - Troubleshooting - Org-roam]]

週単位で日記のようなページを外部公開用に使う.

ツイッターのようなマイクロブログの利用を想定している.

#+begin_src emacs-lisp :tangle yes
(after! org-roam
  (setq org-roam-dailies-directory "zk")

  (setq org-roam-dailies-capture-templates
        '(("d" "default" entry "** %?" :if-new
           (file+head+olp "%<%G-w%V>.org" "#+title: 📓%<%G-w%V>\n"
                          ("🖊Journals"))))))
#+end_src

#+begin_src emacs-lisp :tangle yes
(after! org-capture
  (add-to-list 'org-capture-templates
        '("w" "💭 Thought(weekly)" entry
          (file+headline (lambda ()
                     (my/create-weekly-org-file my/weekly-journal-dir))
                         "🖊Journals")
              "* 💭%?\n%T\n\n" 
              :empty-lines 1 
              :unnarrowed nil ;; ほかのエントリは見えないように.
              :klll-buffer t)))
#+end_src

*** org-roam-ui(disabled)

Web UI.

#+begin_src emacs-lisp :tangle no
(use-package! websocket
    :after org-roam)
(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
    ;; :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))


#+end_src

*** org-roam-timestamps(disabled)

org-roam-uiでつかうメタ情報を付与することが目的だが現状使っていないのでいったん封印.

#+begin_src emacs-lisp :tangle no
(use-package! org-roam-timestamps
   :after org-roam
   :config
   (org-roam-timestamps-mode)
   (setq org-roam-timestamps-remember-timestamps nil)
   (setq org-roam-timestamps-remember-timestamps nil))
#+end_src

*** org-roamのslowdownを回避するTip

https://www.reddit.com/r/orgmode/comments/s8xv5j/orgroam_slows_down_as_nodes_increase_solution/

#+begin_src emacs-lisp :tangle yes
;; 2. Memoize the function that costs the most.
(load-file "~/.doom.d/private/memoize.el")
(require 'memoize)

(memoize 'org-roam-node-read--completions "10 minute")

(defun memoize-force-update (func &optional timeout)
  (when (get func :memoize-original-function)
    (progn (memoize-restore func)
           (memoize func timeout))))
(defun my/force-update-org-roam-node-read-if-memoized (&optional timeout)
  (interactive)
  (memoize-force-update 'org-roam-node-read--completions
                        (if timeout timeout memoize-default-timeout)))
(run-with-idle-timer 60 t #'my/force-update-org-roam-node-read-if-memoized)
;; Note: it might be better to hack org-roam to make it use
;; hash-tables instead of lists. Have a way to quickly detect
;; which node is to be updated.
#+end_src


** org-toggl

org-modeをTogglと連携させる.
https://github.com/mbork/org-toggl

#+begin_src emacs-lisp :tangle no
(use-package! org-toggl
  :after org
  :config
  (setq org-toggl-inherit-toggl-properties t)
  (toggl-get-projects)
  (setq toggl-default-project "GTD")
  (org-toggl-integration-mode))
#+end_src

** org-journal

https://github.com/bastibe/org-journal

#+begin_src emacs-lisp :tangle yes
(use-package! org-journal
  :after org
  :bind
  ;; org-roamと揃えたいので C-c rまでをprefixにする.
  ("C-c r d n" . org-journal-new-entry)
  ("C-c r d d" . org-journal-open-current-journal-file)
  :config
  (setq org-journal-date-prefix "#+TITLE: ✍")
  ;; (setq org-journal-file-type `daily)
  ;; (setq org-journal-file-format "%Y-%m-%d.org")
  ;; (setq org-journal-date-format "%Y-%m-%d")
  ;; これはorg-journalの変数ではない.
  (setq org-journal-file-format "%Y-w%V.org")
  (setq org-journal-date-format "%Y-w%V")
  (setq org-journal-file-type `weekly)
  (setq org-journal-dir my/weekly-private-dir)
  ;; (setq org-journal-enable-agenda-integration t)
)
#+end_src

** org-ref(bibtex)

文献管理. Zoteroと連携して，論文というよりは書籍やYoutube動画やWeb記事のメモに利用.

- org-ref
- ivy-bibtex
  - ivyのactionは ivy-bibtexでC-SPCで選択-> C-M-oでaction選択候補を出し，pとかeとか押す.
- org-roam-bibtex

なんかzoteroからデータエクスポートできなくなって動かなくなった.

なんかorg-mode開くたびにreloadが走るのでmaskした.

#+begin_src emacs-lisp :tangle no
(use-package! org-ref
  :config
  (setq bibtex-completion-bibliography (list (file-truename "~/repo/keido/references/zotLib.bib")))

  (setq bibtex-completion-additional-search-fields '(keywords))
  (setq bibtex-completion-display-formats
    '((online       . "${=has-pdf=:1}${=has-note=:1} ${=type=:6} ${year:4} ${author:24} ${title:*}")
      (book         . "${=has-pdf=:1}${=has-note=:1} ${=type=:6} ${year:4} ${author:24} ${title:*}")
      (video        . "${=has-pdf=:1}${=has-note=:1} ${=type=:6} ${year:4} ${editor:24} ${title:*}")
      (paper        . "${=has-pdf=:1}${=has-note=:1} ${=type=:6} ${year:4} ${author:24} ${title:*}")
      (t            . "${=has-pdf=:1}${=has-note=:1} ${=type=:6} ${year:4} ${author:24} ${title:*}")))
  (setq bibtex-completion-pdf-symbol "📓")
  (setq bibtex-completion-notes-symbol "📝")

  (setq bibtex-completion-pdf-field "file")
  ;; (setq bibtex-completion-pdf-open-function
  ;;	(lambda (fpath)
  ;;	  (call-process "open" nil 0 nil fpath)))

  ;; Create fields for Film type
  (add-to-list 'bibtex-biblatex-field-alist
               '(("video" "Video or Audio(like YouTube)")))

  (add-to-list 'bibtex-biblatex-entry-alist
               '("video" "A Video"
                 ("video", "title" "editor" "date" "url" "urldate" "abstract" "editortype")
                 nil
                 "keywords"))
  (bibtex-set-dialect 'biblatex))

(use-package! ivy-bibtex
  :after org-ref
  :init
  (map!
   :leader
   :prefix ("b" . "org-ref")
     "b" #'org-ref-bibtex-hydra/body
     "v" #'ivy-bibtex
     "c" #'org-ref-insert-cite-link
     "a" #'orb-note-actions
     "i" #'orb-insert-link)
  :config
  (setq ivy-re-builders-alist
        '((ivy-bibtex . ivy--regex-ignore-order)
          (t . ivy--regex-plus)))
  (setq ivy-bibtex-default-action #'ivy-bibtex-open-url-or-doi)
  (ivy-set-actions
   'ivy-bibtex
   '(("p" ivy-bibtex-open-any "Open PDF, URL, or DOI" ivy-bibtex-open-any)
     ("e" ivy-bibtex-edit-notes "Edit notes" ivy-bibtex-edit-notes)))
  )

(use-package! org-roam-protocol
  :after org-protocol)
#+end_src

つかってないのでエラーたのでいったんマスク.

#+begin_src emacs-lisp :tangle no
(use-package! org-roam-bibtex
  :after org-roam ivy-bibtex
  :hook (org-mode . org-roam-bibtex-mode)
  :custom
  (orb-insert-interface 'ivy-bibtex)
  :config
    (setq orb-preformat-keywords '("author" "date" "url" "title" "isbn" "publisher" "urldate" "editor" "file"))
    (setq orb-process-file-keyword t)
    (setq orb-attached-file-extensions '("pdf")))
#+end_src

** org-anki

Org-modeとAnkiをつなぐ.

https://github.com/eyeinsky/org-anki

今までanki-editorを利用していたものの，その記法とwikiの相性が悪かった（冗長）. これならorg-modeのheadlineがそのままつかえるのでよさそう.

#+begin_src emacs-lisp :tangle yes
(use-package! org-anki
  :after org
  :custom
  ;; one big deckの原則に従う.
  ;; ref: http://augmentingcognition.com/ltm.html
  (org-anki-default-deck "Default")
  :config
  (define-key org-mode-map (kbd "C-c n A s") #'org-anki-sync-entry)
  (define-key org-mode-map (kbd "C-c n A u") #'org-anki-update-all)
  (define-key org-mode-map (kbd "C-c n A d") #'org-anki-delete-entry))
#+end_src

URLの挿入はorg-link形式でできる. これは便利.
** org-bars(deprecated)

今どきのアウトライナー的な線を出す.

- Terminal Mode ではつかえない.
- リストの折返しでのインデントは崩れる.

#+begin_src emacs-lisp :tangle no
(require 'org-bars)
(add-hook! 'org-mode-hook #'org-bars-mode)
#+end_src

<2025-11-12 Wed 16:25> 表示が気持ち悪くなったので無効化.

** Org-noter(disabled)

PDFの注釈を管理する. [[https://github.com/weirdNox/org-noter][:link:weirdNox/org-noter]]

はじめの起動がどうやればいいのかワカラなかった. 特定のファイルに記録を残したい場合はPDFのBufferではなく, 適当なheading作成してM-x org-noterを起動するとPDFを選択できる.

M-x org-noter-create-skeltonという関数がヤばい. [[https://youtu.be/lCc3UoQku-E?t=68][🔗Youtube動画(1:08)]] PDFからOutlineを抜き出してOrg fileに生成して，あとはそのOrg-fileのBulletのカーソルを移動するとPDFのほうもシンクロして移動できる. 

凄すぎて笑った😂

#+begin_src emacs-lisp :tangle no
(use-package! org-noter
  :after (:any org pdf-view)
  :config
  (setq
   ;; I want to see the whole file
   org-noter-hide-other nil
   ;; Everything is relative to the main notes file
   org-noter-notes-search-path (list (file-truename "~/repo/keido/notes/wiki"))))
#+end_src

** org-trello(disabled)

Kanbanツール Trello連携. 

- refs.
  - [[http://org-trello.github.io/][org-trello(official)]]
  - [[https://github.com/org-trello/org-trello][GitHub - org-trello/org-trello]]

古いプロジェクトだがメンテもされていてスターも500以上ついている.

ただし動かない...native comp無効で行けるか. -> いけた.
https://github.com/org-trello/org-trello/issues/418

#+begin_src emacs-lisp :tangle no
(use-package! org-trello)
#+end_src

どうもDoom Emacsだと C-uが効かない. そしてそれによってtrello->org-fileへのdownloadがC-u C-c o sに頼っているので不便になる. *(org-trello-sync-buffer t)* を評価するとダウンロードが走るという仕様のためこれを関数にして呼ぶことによって代替.

[[https://github.com/org-trello/org-trello/issues/409][Synching from and to Trello does not work · Issue #409]]

#+begin_src emacs-lisp :tangle no
(after! org-trello
  (defun my/org-trello-sync-from-trello ()
    (interactive)
    (org-trello-sync-buffer t)))
#+end_src

** org-table

#+begin_src emacs-lisp :tangle yes
(setq org-table-export-default-format "orgtbl-to-csv")
#+end_src

** org-sidebar

https://github.com/alphapapa/org-sidebar

org-sidebar-treeでサイドバーにアウトラインを表示.

#+begin_src emacs-lisp :tangle no
(use-package! org-sidebar
  :config
  ;; cider-modeに合わせて C-c C-zにbindしてみた.
  (define-key org-mode-map (kbd "C-c C-z") #'org-sidebar-tree-toggle))
#+end_src

** Org timestamps

org-mode で timestamp のみを挿入するカスタム関数. Doom EmacsのせいでC-u C-c .が動作しないので.

#+begin_src emacs-lisp :tangle yes
(after! org
  (defun my/insert-timestamp ()
    (interactive)
    (org-insert-time-stamp (current-time) t))
  (defun my/insert-timestamp-inactive ()
    (interactive)
    (org-time-stamp-inactive (current-time)))
  (map! :map org-mode-map "C-u C-c C-." #'my/insert-timestamp-inactive)
  (map! :map org-mode-map "C-c C-." #'my/insert-timestamp))
#+end_src

---

空白が保存時に削除されると bullet 表示がおかしくなる.
なお wl-bulter は doom emacs のデフォルトで組み込まれている.

#+begin_src emacs-lisp :tangle yes
(add-hook! 'org-mode-hook
  (when (fboundp 'ws-butler-mode)
    (ws-butler-mode -1)))
#+end_src

** org-pomodoro

#+begin_src emacs-lisp :tangle no
(use-package! org-pomodoro)
#+end_src

** org-web-tools

ewwとorgを便利にするツール群(https://github.com/alphapapa/org-web-tools).

#+begin_src emacs-lisp :tangle yes
(use-package! org-web-tools
  :bind
  ("C-c i l" . org-web-tools-insert-link-for-url))
#+end_src


** org-ai

https://github.com/rksm/org-ai

openai-api-tokenの設定が必要. private/config.elで定義している.

#+begin_src emacs-lisp :tangle yes
(use-package! org-ai
  :load-path (lambda () "~/.emacs.d/.local/straight/repos/org-ai")
  :commands (org-ai-mode)
  ;; :custom
  ;; (org-ai-openai-api-token "")
  :init
  (add-hook 'org-mode-hook #'org-ai-mode)
  :config
  ;; if you are using yasnippet and want `ai` snippets
  (org-ai-install-yasnippets))
#+end_src

* Term
#+begin_src emacs-lisp :tangle yes
;; Term
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 (after! vterm                                                                               (add-hook 'vterm-mode-hook #'hl-line-mode))
#+end_src

* Tools
#+begin_src emacs-lisp :tangle yes
;; Tools
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src

** forge

magit拡張, EmacsとGitHubを連携.

doom emacsだと [[https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/magit/README.org][(magit +forge)]] のオプションでインストールできる.

ref: [[https://magit.vc/manual/forge/][Forge User and Developer Manual]]

#+begin_src emacs-lisp :tangle yes
(after! magit
  (setq auth-sources '("~/.authinfo"))
  (setq magit-revision-show-gravatars '("^Author:     " . "^Commit:     "))
  ;; (setq magit-diff-refine-hunk 'all)
)
#+end_src

リポジトリ名を変更した場合はissueやPRの作成が失敗する.
これは .git/configの問題なのでローカルのファイルを修正する.

** git-link

現在のバッファの位置のGitHubのurlを取得.

[[https://github.com/sshaw/git-link][sshaw/git-link]]

#+begin_src emacs-lisp :tangle yes
(global-set-key (kbd "C-c s g") 'git-link)
(use-package! git-link
  :config
  ;; urlにbranchではなくcommit番号をつかう.
  ;; org-journalへの貼り付けを想定しているのでこの設定にしておく.
  (setq git-link-use-commit t))
#+end_src

* UI

みため周りの設定.

** Doom

#+begin_src emacs-lisp :tangle yes
;; UI
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; どうもフォントが奇数だと org-table の表示が崩れる.
;; Source Han Code JP だとそもそも org-table の表示が崩れる.
;; terminal だと大丈夫な模様.そもそも Terminal はこの設定ではなくて 
;; Terminal Emulator の設定がきく.

;; Twitterで拾った設定だけど若干org-table表示がマシになったので採用.
;; (set-face-attribute 'fixed-pitch nil :font "Ricty Diminished" :height 160)
;; (setq doom-font (font-spec :family "Source Han Code JP" :size 15 ))
;; (setq doom-font (font-spec :family "Ricty Diminished" :size 16))
(when (wsl-p) 
  (setq doom-font (font-spec :family "HackGen" :size 18)))
(when (not (wsl-p))
  (setq doom-font (font-spec :family "Source Han Code JP" :size 15 )))
;; doom-molokaiやdoom-monokai-classicだとewwの表示がいまいち.
(setq doom-theme 'doom-molokai)
(doom-themes-org-config)

;; counselとdoom-modelineが相性悪いようなので
;; workspace name表示のためには追加で設定.
;; https://github.com/hlissner/doom-emacs/issues/314
;; (after! doom-modeline
;;  (setq doom-modeline-icon (display-graphic-p))
;;  (setq doom-modeline-major-mode-icon t))
#+end_src

https://github.com/seagle0128/doom-modeline

** emojify

Emacsで絵文字をつかう.

どうもemojifyの絵文字辞書は，emojione-v2.2.6-22というものでやや古い.
Twitterが好きなのでTwitterのオープンソース辞書のtwemojiに変更.

https://github.com/iqbalansari/emacs-emojify/blob/master/data/emoji-sets.json

#+begin_src emacs-lisp :tangle yes
(after! emojify
;;   (setq emojify-emoji-set "openmoji-v13-0")
  ;; (setq emojify-emoji-set "emojione-v2.2.6.22")
)
#+end_src

ただ，2022現在twemojiはv13なのでv2は古いな..というかでないやつもおおい.

Emacsの機能でemoji-searchがあるのでこれも設定しておこう. 
こっちの辞書のほうが扱える文字か多い.

#+begin_src emacs-lisp :tangle yes
;; doomだと C-c i eでemojify-insert-emoji
(global-set-key (kbd "C-c i E") 'emoji-search)
#+end_src

** svg-tag-mode

TODOほかラベルを美しく. 

[[https://github.com/rougier/svg-tag-mode][GitHub - rougier/svg-tag-mode]]

#+begin_src emacs-lisp :tangle yes
(use-package! svg-tag-mode
  :config
  (setq svg-tag-tags
        '(
          ;; :XXX:
          ("\\(:[A-Z]+:\\)" . ((lambda (tag)
                                 (svg-tag-make tag :beg 1 :end -1))))          
          ;; :XXX|YYY:
          ("\\(:[A-Z]+\\)\|[a-zA-Z#0-9]+:" . ((lambda (tag)
                                                (svg-tag-make tag :beg 1 :inverse t
                                                              :margin 0 :crop-right t))))
          (":[A-Z]+\\(\|[a-zA-Z#0-9]+:\\)" . ((lambda (tag)
                                                (svg-tag-make tag :beg 1 :end -1
                                                              :margin 0 :crop-left t))))
          ;; :#TAG1:#TAG2:…:$
          ("\\(:#[A-Za-z0-9]+\\)" . ((lambda (tag)
                                       (svg-tag-make tag :beg 2))))
          ("\\(:#[A-Za-z0-9]+:\\)$" . ((lambda (tag)
                                       (svg-tag-make tag :beg 2 :end -1))))
          )))
#+end_src

** Others

#+begin_src emacs-lisp :tangle yes
;; これがスクロールを遅くする可能性があるので実験的に抑止.
(setq display-line-numbers-type nil) ; 行番号表示

;; less でのファイル閲覧に操作性を似せる mode.
;; view-mode は emacs 内蔵. C-x C-r で read-only-mode でファイルオープン
;; doom emacs だと C-c t r で read-only-mode が起動する.
(add-hook! view-mode
  (setq view-read-only t)
  (define-key ctl-x-map "\C-q" 'view-mode) ;; assinged C-x C-q.

  ;; less っぼく.
  (define-key view-mode-map (kbd "p") 'view-scroll-line-backward)
  (define-key view-mode-map (kbd "n") 'view-scroll-line-forward)
  ;; default の e でもいいけど，mule 時代に v に bind されてたので, 
  ;; emacs でも v に bind しておく.
  (define-key view-mode-map (kbd "v") 'read-only-mode))

;; EXWMの場合suspend-frameでハングするのはたちが悪いので封印.
(use-package! frame
  :bind
  ("C-z" . nil))

;; 実験, どうもマウス操作でEmacsの制御が効かなくなることがあるので.
(setq make-pointer-invisible nil)

;; (general-def
;;  :keymaps 'override
;;   "C-u" 'universal-argument)
#+end_src

* AI

いろいろあるので試すがつかうのは一つにしたいところ. 

- https://github.com/karthink/gptel

** chatgpt

https://github.com/emacs-openai/chatgpt

** chatgpt-shell

chatgpt-shell-openai-keyはconfig.elに記載. ChatGPT以外でもいける.

https://github.com/xenodium/chatgpt-shell

#+begin_src emacs-lisp :tangle yes
(use-package! chatgpt-shell
  :commands chatgpt-shell
  :init
  (bind-key "C-c z b" 'chatgpt-shell)
  :config
  (setq chatgpt-shell-chatgpt-streaming t))
#+end_src

** Ellama

https://github.com/s-kostyaev/ellama/

#+begin_src emacs-lisp :tangle no
(use-package! ellama
    :bind ("C-c e" . ellama-transient-main-menu)
    :init
    ;; setup key bindings
    ;; (setopt ellama-keymap-prefix "C-c e")
    ;; language you want ellama to translate to
    (setopt ellama-language "Japanese")
    ;; could be llm-openai for example
    (require 'llm-ollama)
    (setopt ellama-provider
	  (make-llm-ollama
	       ;; this model should be pulled to use it
	       ;; value should be the same as you print in terminal during pull
	       :chat-model "llama3.2:latest"
	       :embedding-model "nomic-embed-text"
	       :default-chat-non-standard-params '(("num_ctx" . 8192))))
    ;; (setopt ellama-summarization-provider
    ;;           (make-llm-ollama
    ;;            :chat-model "qwen2.5:3b"
    ;;            :embedding-model "nomic-embed-text"
    ;;            :default-chat-non-standard-params '(("num_ctx" . 32768))))
    ;; (setopt ellama-coding-provider
    ;;           (make-llm-ollama
    ;;            :chat-model "qwen2.5-coder:3b"
    ;;            :embedding-model "nomic-embed-text"
    ;;            :default-chat-non-standard-params '(("num_ctx" . 32768))))
    ;; Predefined llm providers for interactive switching.
    ;; You shouldn't add ollama providers here - it can be selected interactively
    ;; without it. It is just example.
    ;; ellamaで使えるプロバイダー。ellama-provider-select で選択できる
    (setopt ellama-providers
	      '(("zephyr" . (make-llm-ollama
			     :chat-model "zephyr:7b-beta-q6_K"
			     :embedding-model "zephyr:7b-beta-q6_K"))
		("mistral" . (make-llm-ollama
			      :chat-model "mistral:7b-instruct-v0.2-q6_K"
			      :embedding-model "mistral:7b-instruct-v0.2-q6_K"))
		("mixtral" . (make-llm-ollama
			      :chat-model "mixtral:8x7b-instruct-v0.1-q3_K_M-4k"
			      :embedding-model "mixtral:8x7b-instruct-v0.1-q3_K_M-4k"))))
    ;; Naming new sessions with llm
    (setopt ellama-naming-provider
	      (make-llm-ollama
	       :chat-model "llama3.2:latest"
	       :embedding-model "nomic-embed-text"
	       :default-chat-non-standard-params '(("stop" . ("\n")))))
    (setopt ellama-naming-scheme 'ellama-generate-name-by-llm)
    ;; Translation llm provider, 翻訳で利用するプロバイダー
    (setopt ellama-translation-provider
	    (make-llm-ollama
	     :chat-model "elyza:jp8b"
	     :embedding-model "nomic-embed-text"
	     :default-chat-non-standard-params
	     '(("num_ctx" . 32768))))
    ;; customize display buffer behaviour
    ;; see ~(info "(elisp) Buffer Display Action Functions")~
    (setopt ellama-chat-display-action-function #'display-buffer-full-frame)
    (setopt ellama-instant-display-action-function #'display-buffer-at-bottom)
    :config
    ;; send last message in chat buffer with C-c C-c
    (add-hook 'org-ctrl-c-ctrl-c-hook #'ellama-chat-send-last-message))
#+end_src

** Claude code IDE

https://github.com/manzaltu/claude-code-ide.el

#+begin_src emacs-lisp :tangle yes
(use-package! claude-code-ide
  :bind (("C-c z c" . claude-code-ide)
         ("C-c C-7" . claude-code-ide-menu)
         ("C-c C-r" . claude-code-ide-insert-at-mentioned))
  :config
  (setq exec-path (append exec-path '("~/.local/bin")))
  (setq claude-code-ide-window-side 'left)
  (claude-code-ide-emacs-tools-setup))
#+end_src

*** vterm

内部ではvtermをつかっている. read-only-modeとなっている. vterm-yankで貼り付け.

C-y はEvil modeの別バインドが優先されるため、vterm バッファで明示的に vterm-yank を割り当てる。

#+begin_src emacs-lisp :tangle yes
(after! vterm
  (define-key vterm-mode-map (kbd "C-y") #'vterm-yank))
#+end_src

